#!/bin/sh
CDIR=$(cd "${0%/*}"; pwd)

echo "$CDIR" | sudo tee /etc/paths.d/net.yonsm.macx

sudo grep "admin ALL=(ALL) NOPASSWD: ALL" /etc/sudoers >/dev/null 2>&1
if [ $? = 1 ]; then
    echo "admin ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
fi

sudo spctl --master-disable

defaults write com.apple.iTunes DeviceBackupsDisabled -bool YES
defaults write com.apple.desktopservices DSDontWriteNetworkStores true
defaults write com.apple.iTunes AutomaticDeviceBackupsDisabled -bool true

#$CDIR/XRamDisk

exit


# Speed Test
cd $CDIR
curl -o speedtest https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x speedtest

# Brew
#/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"
brew update

brew install scrcpy

# Python
mkdir ~/.pip
cat << \EOF > ~/.pip/pip.conf
[global]
index-url=http://mirrors.aliyun.com/pypi/simple/
[install]
trusted-host=mirrors.aliyun.com
EOF

pip3 install esptool miservice

# Sublime
# +Package Control: Command+Shift+P
#   +ChineseLocalizations
#   +ConvertToUTF8
#   +Codec33
#   +JsFormat
#   +Pretty JSON
#   +SFTP
# Settings
#   "rulers": [80,120,160,200],
#   "word_wrap": "false",
#   "update_check": false,
#   "translate_tabs_to_spaces": true,
#   "trim_trailing_white_space_on_save": true,
# Host
echo: https://github.com/QiuChenly/MyMacsAppCrack
echo "0249FFC6 EBE15B41 5C415E41 5F5DC355 4889E5 => 0249FFC6 EBE15B41 5C415E41 5F5DC36A 0158C3"
sudo codesign -f -s - --timestamp=none ~/Applications/Sublime.app

# SN
cat << EOF | sudo tee -a /etc/hosts
127.0.0.1 www.sublimetext.com
127.0.0.1 license.sublimehq.com
EOF

cat << \EOF
#Sublime
----- BEGIN LICENSE -----
cracked@macked.app
Unlimited User License
EA7E-8888888
3AED0BDB9CD5123CDE42973715763305
6F251DBED243E59935EB274AA468E33E
D7790513000ECF845A71A3A446E820E1
7CC9719C9DFCAFB29189974012CFDF33
9D3275454E37B76745F1B8E771E2ABC5
A7058D431570EEA27A43B69EFCC9C482
D2027C11326EDD346CC229FC7FD483C8
771EE17E2F4A0A20F8A39D814DCD1504
------ END LICENSE ------

#Axure
zedex.cn
xpU4wqREqR6MNDjj957APLHET1GwFV1d6bMjkconScgt01Z2nSwH1pz55FQs5MIh

#AppDelete
AD-V845-I172-R956-B601

PlistEdit
PLEDPRO095-42E7-REKA-M4H4-1309-1405

#Pacifist
MacXMacX
4nbSTd3G6C-2bS2quo1of-AIC

#VMWare
4C21U-2KK9Q-M8130-4V2QH-CF810

#Proxifier
P427L-9Y552-5433E-8DSR3-58Z68

# https://www.zzzmode.com/mytools/charles/
Mac OS
6BACE69077E6DA3993
EOF

# VS Code
#   +PlatformIO
cat << \EOF > ~/Library/Application\ Support/Code/User/settings.json
{
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.detectIndentation": true,
    "editor.insertSpaces": false,
    "editor.minimap.enabled": false,
    "editor.useTabStops": true,
    "html.format.wrapLineLength": 160,
    "prettier.endOfLine": "lf",
    "prettier.htmlWhitespaceSensitivity": "strict",
    "prettier.printWidth": 160,
    "prettier.semi": false,
    "prettier.singleQuote": true,
    "prettier.tabWidth": 4,
    "prettier.useTabs": true,
    "python.autoComplete.addBrackets": true,
    "python.pythonPath": "/usr/bin/python3",
    "workbench.startupEditor": "newUntitledFile",
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Args": ["--max-line-length=200"],
    "autopep8.args": ["--max-line-length=200", "--ignore=W191"]
}
EOF
